[general]
live_config_reload = true

[window]
padding = { x = 5, y = 0 }
blur = true
opacity = 0.5

[font]
normal = {family = "JetBrainsMono Nerd Font", style = "Medium"}

[cursor]
style = {shape = "Beam", blinking = "On"}

[terminal]
shell = "/bin/fish"
